### PR TITLE
Some typo fixing and updates in README and example.ipynb

### PR DESCRIPTION
**Pull request by jensch-dlr**
## Change proposed in this Pull Request

This PR is just contributing some minor typo fixes and updates to information that is not accurate anymore.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (mere editorial amendments)

## Checklist
- [ ] I have added a note to release notes `doc/release_notes.rst`.
- [x] I have used `pre-commit run --all` to lint/format/check my contribution
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have adjusted the docstrings in the code appropriately.

### CODE REVIEW

**Review by FabianHofmann — APPROVED** [review]
thanks @jensch-dlr

**Comment by jensch-dlr** [comment]
Oh, wow. I currently don't get how I could possibly break stuff by only fixing typos and implementing suggested changes due to deprecated methods. Still trying to figure that out...

**Comment by fneum** [comment]
HTTP timeouts or new version rollouts of dependencies can cause this.

**Comment by jensch-dlr** [comment]
Thank you. Now all checks have passed magically. Was apparently that HTTP timeout thing?

**Review by fneum — APPROVED** [review]

**Pull request merged**
