### PR TITLE
add convert to short name in GEO

### PR DESCRIPTION
**Pull request by davide-f**
Closes # (if applicable).

## Change proposed in this Pull Request

GEO function missed the short_name filtering that is now added.
This partially address #95 
Does this need a release_note line?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

## Checklist

- [ ] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have adjusted the docstrings in the code appropriately.

### CODE REVIEW

**Comment by pz-max** [comment]
@davide-f Made Taiwan run & safes my life :partying_face: 
I think we need something similar for GPD (it has Taiwan data but it was not found for matching)

**Comment by davide-f** [comment]
> @davide-f Made Taiwan run & safes my life 🥳 I think we need something similar for GPD (it has Taiwan data but it was not found for matching)

Happy to help!
Check if you solve with the latest commit

**Comment by davide-f** [comment]
@FabianHofmann could you please checkout these two PRs? https://github.com/PyPSA/powerplantmatching/pull/97 and https://github.com/PyPSA/powerplantmatching/pull/96 (this one)

They are very small but highly needed for pypsa-earth.
A new release after that would be awesome as well if easy to do.

Many thanks

**Review by FabianHofmann — APPROVED** [review]

**Comment by FabianHofmann** [comment]
thanks @davide-f, does not need a release note necessarily

**Pull request merged**
