### PR TITLE
Update GEM solar and wind datasets to May-2023. 

### PR DESCRIPTION
**Pull request by Tomkourou**
Closes # (if applicable).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

## Checklist

- [x] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have adjusted the docstrings in the code appropriately.

### CODE REVIEW

**Comment by davide-f** [comment]
Hello!
Nice update! I think comment by @FabianHofmann may be welcome.
Personally, I think we should avoid the manual update from Jan to May, etc.
I understand that the pointed resource is stored in @pz-max github. I think it would be best to always name in github a file "..._latest" so that there is no need to open a PR every month.

What do you think? @FabianHofmann @Tomkourou @pz-max

**Comment by pz-max** [comment]
Agree with @davide-f. Great suggestion! This allows us to be more flexible.
I am creating a copy and call it latest in my data repo

**Comment by Tomkourou** [comment]
Agree that's probably wise :)

**Comment by FabianHofmann** [comment]
Very good idea!

**Comment by FabianHofmann** [comment]
Let's merge this for now and set up the "latest" reference later

**Pull request merged**
